on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 3 * *' 

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
  AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
  AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          pip install pandas
          pip install openai

      - name: extract insights from team feedback
        run: |
          python extract_insights_from_last_team_survey.py
